name: CI7

on:
  push:
  pull_request:
    branches: [main gh-pages]
  schedule:
    #   分 时 日 月 周
    - cron: '*/1 * * * *'
  repository_dispatch:
    types:
      - auto7
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'GitHubAction')"
    steps:
      - uses: actions/checkout@v2

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
         server_address: smtp.163.com
         server_port: 465
#          server_address: smtp.gmail.com
#          server_port: 465
        #  server_address: smtp.exmail.qq.com
        #  server_port: 465
         username: ${{ secrets.MAIL_NAME }}
         password: ${{ secrets.MAIL_PWD }}
         subject: "【警惕网络诈骗,人人有责】"
         to: ecochainliesstop@gmail.com
         from:  ChinaPolicy
         secure: true
         body:  |
           【警惕网络诈骗,人人有责2】
         html_body: file://1926_1708514905.mp4
         attachments: 1926_1708514905.mp4,1926_1708514905.mp4,1926_1708514905.mp4,1926_1708514905.mp4,1926_1708514905.mp4
         ignore_cert: true
         priority: high

